version: "3.10"

services:
  redis:
    image: redis
    restart: always

  webapp:
    restart: always
    build:
      context: ./webapp
    ports:
      - "8000:8000"
    command: ["python", "./proj/manage.py", "runserver", "0.0.0.0:8000"]

  worker:
    restart: always
    build:
      context: ./webapp
    volumes:
      - ./cats:/app/proj/cats
    command: ["celery", "--workdir=./proj", "-A", "proj", "worker"]